---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: site/content
  label: Pages
  create: all
- path: site/content/food
  label: Food
  create: all
- path: site/content/gallery
  label: Gallery
  create: all
- path: site/content/drinks
  label: Drinks
  create: all
- path: site/content/pages
  label: Pages
  create: all
upload_dir: src/img/gallery
public_path: "/img/gallery"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.2
