backend:
  name: github
  repo: emilkje/hugo-tasty
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/img/gallery"

collections:
  - name: food
    label: "Food Item"
    folder: "site/content/food"
    create: true
    fields:
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch", "dinner"]}
      - {label: "Ingedients/Description", name: "description", widget: "text"}
      - {label: "Type of Food", name: "type", widget: "string", default: "raw bar"}
      - {label: "Price", name: "price", widget: "string"}
  - name: drinks
    label: "Drink Item"
    folder: "site/content/drinks"
    create: true
    fields:
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Drink marker", name: "categories", widget: "hidden", default: ["drinks"]}
      - {label: "Ingedients/Description", name: "description", widget: "text"}
      - {label: "Type of Drink", name: "type", widget: "string", default: "beer"}
      - {label: "Price", name: "price", widget: "string"}
  - name: gallery
    label: "Gallery Image"
    folder: "site/content/gallery"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Gallery Image", name: "image", widget: "image"}